### ISSUE TITLE
shadowsocks cannot run 

### ISSUE THREAD

**Issue by lidaling** [shadowsocks/shadowsocks-nodejs#118]
shadowsocks v1.5.3
19 Dec 09:50:56 - 960ms loading config from /etc/shadowsocks/config.json
19 Dec 09:50:56 - 960ms calculating ciphers for port 12304
I can not run .This is the error.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EADDRNOTAVAIL
    at errnoException (dgram.js:458:11)
    at dgram.js:211:28
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by RodriAliaga** [comment]
I have the same error, how did you solve it?

**Comment by jackyting825** [comment]
Can you give a solve ways?
