### ISSUE TITLE
ssserver not connecting

### ISSUE THREAD

**Issue by vishalsolankii** [shadowsocks/shadowsocks-nodejs#126]
I have created a json and run following command 

ssserver    it gave me a error 

shadowsocks v1.5.3
5 Mar 18:27:22 - 56ms loading config from config.json
5 Mar 18:27:22 - 57ms calculating ciphers for port 58669
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRNOTAVAIL 146.0.40.113:58669
    at _handle.lookup (dgram.js:279:18)
    at process._tickCallback (internal/process/next_tick.js:174:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
Emitted 'error' event at:
    at _handle.lookup (dgram.js:280:14)
    at process._tickCallback (internal/process/next_tick.js:174:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

Please help me to implement this

**Comment by chenshaoju** [comment]
The shadowsocks-nodejs is discarded.
Please use libev version: https://github.com/shadowsocks/shadowsocks-libev
